### ISSUE TITLE
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security'

### ISSUE THREAD

**Issue by pattertj** [app-generator/flask-datta-able#4]
The project no longer runs correctly per the instructions. You are met with the error "ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security'"

This functionality was recently deprecated and removed, see here: https://github.com/pallets/werkzeug/issues/2359

This is impacting flask-login, which it seems is not updated yet: https://github.com/maxcountryman/flask-login/blob/0f94639858946ea8e921743db684b6da97d46385/CHANGES.md

**Comment by app-generator** [comment]
Hello @pattertj 

Ty for reporting this. We will provide a patch asap.

**Comment by app-generator** [comment]
P.S. Full context can be found here:

[ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security'](https://docs.appseed.us/content/how-to-fix/importerror-cannot-import-name-safe_str_cmp-from-werkzeug.security)
