### ISSUE TITLE
Possible to host flask-datta-able website at different APPLICATION_ROOT

### ISSUE THREAD

**Issue by jongarrison** [app-generator/flask-datta-able#5]
Hi, I'm experimenting with using your great flask-datta-able project as wsgi server behind an nginx reverse proxy that hosts multiple sites.  I'm trying to figure out how to configure this and I'm wondering if it is currently possible?  Normally with a flask app, I think you would include (in apps/__init__.py):

app.config['APPLICATION_ROOT'] = '/somesubfolder'

but it appears that there are a number of hardcoded urls throughout flask-datta-able that would prevent this from working, for example in: apps/templates/includes/scripts.html

Is it possible to configure flask-datta-able to run at some subdirectory of a website? 

Thanks for any guidance.

**Comment by app-generator** [comment]
Hello @jongarrison 

Just to be sure, you need to use all features provided by `flask datta able` using a subfolder (not subdomain) of an existing project. 

If my assumption is correct, this use case is quite new and we don't have a tested solution.

**Comment by jongarrison** [comment]
Thanks for the quick reply! In my scenario, I think I am going to go with a subdomain for deployment, but it would have been nice to be able to configure a subfolder style deployment. Some projects I've used in the past were able to be configured this way and I thought it might be possible here. 

If I'm the only one requesting this feature, please don't worry about it.  Thank you for the quick response and great template project!
